import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useLanguage } from "@/contexts/LanguageContext";
import { supabase } from "@/integrations/supabase/client";
import BottomNav from "@/components/BottomNav";
import { ArrowLeft, FileText, Share2, Loader2, Printer } from "lucide-react";
import { toast } from "sonner";

const DoctorSummary = () => {
  const navigate = useNavigate();
  const { t, language } = useLanguage();
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);

  const generateSummary = async () => {
    setLoading(true);
    try {
      const { data: profiles } = await supabase.from("patient_profiles").select("*").limit(1);
      const { data: medicines } = await supabase.from("medicines").select("*").eq("is_active", true);

      if (!profiles?.length) {
        toast.error("No patient profile found");
        setLoading(false);
        return;
      }

      const profile = profiles[0];
      const weekAgo = new Date();
      weekAgo.setDate(weekAgo.getDate() - 7);
      const { data: missed } = await supabase
        .from("doses")
        .select("scheduled_time, scheduled_date")
        .eq("missed", true)
        .gte("scheduled_date", weekAgo.toISOString().split("T")[0]);

      const missedDoses = (missed || []).map((d: any) => `${d.scheduled_date} ${d.scheduled_time}`);

      const { data, error } = await supabase.functions.invoke("doctor-summary", {
        body: {
          name: profile.name,
          age: profile.age,
          medicines: (medicines || []).map((m: any) => ({ name: m.name, dosage: m.dosage, timing: m.timing })),
          missedDoses,
          allergies: profile.allergies || [],
          language,
        },
      });

      if (error) throw error;
      setSummary(data.summary);
      setGenerated(true);
    } catch (e: any) {
      console.error("Summary error:", e);
      toast.error("Could not generate summary. Try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try { await navigator.share({ title: "Doctor Visit Summary", text: summary }); } catch {}
    } else {
      await navigator.clipboard.writeText(summary);
      toast.success("Summary copied to clipboard!");
    }
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(`<html><head><title>Doctor Visit Summary</title>
        <style>body{font-family:system-ui,sans-serif;padding:2rem;line-height:1.6;max-width:700px;margin:0 auto}
        h1{font-size:1.25rem;margin-bottom:1rem}pre{white-space:pre-wrap;font-family:inherit}</style></head>
        <body><h1>🏥 Doctor Visit Summary</h1><pre>${summary}</pre>
        <p style="margin-top:2rem;font-size:0.75rem;color:#888">Generated by MedCircle · AI information is for awareness only.</p></body></html>`);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="min-h-screen bg-background pb-24 page-transition">
      <div className="flex items-center gap-3 p-4 border-b border-border">
        <button onClick={() => navigate(-1)} className="text-foreground p-1"><ArrowLeft size={22} /></button>
        <h1 className="text-lg font-bold text-foreground">Doctor Visit Summary</h1>
      </div>

      <div className="px-4 mt-6">
        {!generated ? (
          <div className="text-center space-y-6">
            <div className="w-20 h-20 mx-auto bg-primary/10 rounded-full flex items-center justify-center">
              <FileText size={36} className="text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-foreground">{t("prepare_visit")}</h2>
              <p className="text-muted-foreground text-sm mt-2">{t("prepare_visit_desc")}</p>
            </div>
            <button onClick={generateSummary} disabled={loading}
              className="w-full flex items-center justify-center gap-2 bg-primary text-primary-foreground rounded-2xl py-4 text-base font-bold shadow-lg hover:opacity-90 transition-opacity disabled:opacity-50">
              {loading ? (<><Loader2 size={20} className="animate-spin" />{t("generating_summary")}</>) : (<><FileText size={20} />{t("generate_summary")}</>)}
            </button>
          </div>
        ) : (
          <div className="space-y-4 animate-fade-in">
            <div className="bg-card border border-border rounded-2xl p-5">
              <div className="flex items-center gap-2 mb-4">
                <FileText size={20} className="text-primary" />
                <h2 className="text-base font-bold text-foreground">{t("your_summary")}</h2>
              </div>
              <div className="whitespace-pre-wrap text-sm text-foreground leading-relaxed">{summary}</div>
            </div>
            <div className="flex gap-3">
              <button onClick={handleShare}
                className="flex-1 flex items-center justify-center gap-2 bg-primary text-primary-foreground rounded-2xl py-3.5 text-sm font-bold hover:opacity-90 transition-opacity">
                <Share2 size={18} />{t("share")}
              </button>
              <button onClick={handlePrint}
                className="flex-1 flex items-center justify-center gap-2 bg-secondary text-secondary-foreground rounded-2xl py-3.5 text-sm font-bold hover:bg-accent transition-colors">
                <Printer size={18} />{t("print")}
              </button>
            </div>
            <button onClick={generateSummary} disabled={loading}
              className="w-full text-center text-sm font-semibold text-primary py-2">
              {loading ? t("generating_summary") : t("regenerate")}
            </button>
          </div>
        )}
        <p className="text-xs text-muted-foreground text-center mt-6 italic">{t("ai_disclaimer")}</p>
      </div>

      <BottomNav />
    </div>
  );
};

export default DoctorSummary;
